server.port=8089
server.servlet.context-path=/RECON-MW
spring.application.name=Recon-System


### DEV MSSQL
spring.datasource.jndi-name=openejb:Resource/ReconSystemDS


### uncomment below two lines (logging.level) to show sql logs
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true

spring.jpa.open-in-view=false


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB









